[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Maximized"
title = "Alacritty"

[scrolling]
history = 10000

[cursor.style]
blinking = "On"
shape = "Beam"

[selection]
save_to_clipboard = true

[font]
size = 12.0
offset.x = -1
offset.y = -2

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# Theme: xoff
# Source: https://github.com/zsxoff/xoff-theme

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.cursor]
cursor = "#FFFFFF"

[colors.selection]
text       = "CellForeground"
background = "#0CFA66"

[colors.normal]
black   = "#000000"
red     = "#FA3B05"
green   = "#0CFA66"
yellow  = "#FFE605"
blue    = "#15C1FF"
magenta = "#FA0474"
cyan    = "#82FAF4"
white   = "#A6A6A6"

[colors.bright]
black   = "#555555"
red     = "#FF6136"
green   = "#4BCE4F"
yellow  = "#FFF48C"
blue    = "#88BBCE"
magenta = "#FF54A1"
cyan    = "#BEFFFC"
white   = "#FFFFFF"
