# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

minimum_prek_version = "0.3.1"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-executables-have-shebangs" },
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-xml" },
  { id = "check-yaml" },
  { id = "destroyed-symlinks" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
  {
    id = "check-json",
    exclude = '''
(?x)(
  ^Code/User/settings\.json|
  ^zed/settings\.json|
  ^zed/tasks\.json|
  ^zed/keymap\.json
)
'''
  }
]

[[repos]]
repo = "https://github.com/scop/pre-commit-shfmt"
rev = "v3.13.1-1"
hooks = [{ id = "shfmt" }]

[[repos]]
repo = "https://github.com/koalaman/shellcheck-precommit"
rev = "v0.11.0"
hooks = [{ id = "shellcheck" }]

[[repos]]
repo = "https://github.com/adrienverge/yamllint.git"
rev = "v1.38.0"
hooks = [{ id = "yamllint", args = ["--strict", "-c=.yamllint"] }]
